/**************************************************************

ページ全体で共通するレイアウトが適用される
..._document.tsx、_app.tsxに置き換わったもの
・ヘッダー、フッターなど

***************************************************************/
import { Suspense } from 'react';
import type { Metadata } from 'next'

import './globals.css'
import Header from './Header'
import Footer from "./Footer";
import Loading from './Loading';

// メタデータ。前のverのHEADのこと
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// 共通するコンポーネントを入れることができる
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className="container mx-auto bg-slate-700 text-slate-50">
        <div className="flex flex-col min-h-screen">
          <Header />
            
            {
            /* Suspense ... 子要素が読み込まれるまでfallbackする
                            子が読み込まれるまでローディングを表示(setTimeoutで1.5秒待機)
            */}
            <Suspense fallback={ <Loading /> }>
              <main className="flex-grow">
                { children }
              </main>
            </Suspense>

          <Footer />
        </div>
      </body>
    </html>
  )
}
